// AMR·AGV 관제 검증 — 전체 속도 배율(50~150%)이 이동 속도·라인 운반 속도에 반영되는지, 차종별 정지·시작(AGV 순차 출발),
// 명령 센터 비상정지가 관제보다 우선하는지, 상황별 속도 규칙·예상 문제점/기대효과·디지털트윈 예측. 실행: npm test
import { zoneLine } from '../js/line.js';
import { Simulation } from '../js/sim.js';
import { FactoryAgent } from '../js/agent.js';
import { fleetAdvice, predictFleet } from '../js/fleet.js';
let pass = 0, fail = 0;
const check = (name, ok, info = '') => { ok ? pass++ : fail++; console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${name}${info ? '  — ' + info : ''}`); };
const s = new Simulation('dark', 3, { line: zoneLine(), quiet: true }), ag = new FactoryAgent(s), F = s.fleet;
const run = (sec) => { for (let t = 0; t < sec; t += 0.1) { s.step(0.1); ag.update(0.1); } };
console.log('== 설정 · 속도 배율');
check('관제 대상: 운반 AMR 16대 · AGV 4대 (피지컬AI)', F.hasAMR && F.hasAGV && F.list('amr').length === 16 && F.list('agv').length === 4);
run(240); const s0 = F.summary('amr');
check('기준 속도: AMR 운반 1.6 · 복귀 2.6 m/s, AGV 2.6 m/s · 실제 최고 속도가 설정 이내', F.speeds('amr').line === 1.6 && F.speeds('amr').drive === 2.6 && F.speeds('agv').drive === 2.6 && s0.max <= 2.6 + 1e-6, `실제 최고 ${s0.max.toFixed(2)} m/s`);
F.setScale('amr', 1.3); F.setScale('agv', 0.7);
check('배율 반영: AMR 130% → 운반 2.08 · 복귀 3.38 m/s, AGV 70% → 1.82 m/s', Math.abs(s.conveyors[0].speed - 2.08) < 1e-9 && s.carriers.every((c) => Math.abs(c.speed - 3.38) < 1e-9) && s.vehicles.every((v) => Math.abs(v.speed - 1.82) < 1e-9));
F.setScale('amr', 9); check('배율 범위 50~150%로 제한', F.amr.scale === 1.5); F.setScale('all', 1);
console.log('== 정지 · 시작');
F.pause('agv'); run(20);
check('AGV 정지: AGV만 멈추고 AMR은 계속 운행', F.summary('agv').moving === 0 && F.summary('amr').moving > 0, `AMR 주행 ${F.summary('amr').moving}대`);
F.resume('agv'); const holds = s.vehicles.map((v) => v.holdUntil - s.time);
check('AGV 시작: 1초 간격 순차 출발', holds.every((h, i) => Math.abs(h - i) < 1e-6), holds.map((h) => h.toFixed(1)).join(','));
F.pause('all'); run(10);
check('전체 정지: AMR·AGV 모두 0 m/s', F.summary('amr').moving === 0 && F.summary('agv').moving === 0);
F.resume('all'); run(15);
check('전체 시작 후 운행 재개', F.summary('amr').moving > 0);
s.cmd.issue('ESTOP', 'all', null, { by: '테스트' }); run(3);
check('명령 센터 비상정지가 관제보다 우선 (관제 운행 중이어도 정지)', !F.amr.paused && F.summary('amr').moving === 0 && F.stateOf(s.carriers[0], 'amr')[0] === '명령 정지');
s.cmd.issue('RESET', 'all', null, { by: '테스트' }); run(5);
console.log('== 상황별 속도 규칙 · 예상 문제점/기대효과 · 예측');
check('상황별 속도 규칙 10종 (관제·명령·현장 이벤트·간격·양보·진입·충전)', F.rules().length === 10);
F.setScale('amr', 1.3); const adv = fleetAdvice(F);
check('속도 올림: 기대효과 + 예상 문제점(제동 거리·공존 구역 상한)', adv.some((a) => a.kind === 'gain') && adv.some((a) => a.kind === 'risk' && /제동/.test(a.text)) && adv.some((a) => /상한/.test(a.text)));
F.setScale('amr', 1); F.pause('amr'); check('정지: 자재대기·UPH 저하 경고 + 재시작 안내', fleetAdvice(F).some((a) => a.kind === 'risk' && /UPH/.test(a.text)) && fleetAdvice(F).some((a) => a.kind === 'tip')); F.resume('amr');
const P = predictFleet({ Simulation, Agent: FactoryAgent, mode: 'dark', line: zoneLine(), seed: 3, T: 600, amr: { scale: 1, paused: false }, agv: { scale: 1, paused: true } });
check('디지털트윈 예측: AGV 정지 시 기준 대비 UPH 하락·자재대기 증가', P.cur.uph < P.base.uph && P.cur.starve > P.base.starve, `UPH ${P.base.uph.toFixed(0)} → ${P.cur.uph.toFixed(0)}`);
console.log('== 단계별');
const sm = new Simulation('smart', 3, { line: zoneLine(), quiet: true }), tr = new Simulation('traditional', 3, { line: zoneLine(), quiet: true });
check('자동화: AMR·AGV(3대, 2.3 m/s) 관제 · 레거시: 관제 대상 없음', sm.fleet.hasAMR && sm.fleet.hasAGV && sm.fleet.speeds('agv').drive === 2.3 && !tr.fleet.hasAMR && !tr.fleet.hasAGV);
console.log(`\n결과: ${pass} PASS / ${fail} FAIL`);
if (fail) process.exit(1);
